# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Robert Lennon
title: Linguistics Researcher
email: r.w.lennon@lancaster.ac.uk
website: robertlennon50.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: robertlennon50
github_username:  robertlennon50
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: robert-lennon
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: ResearchGate link
  icon: fas fa-globe
  url: https://www.researchgate.net/profile/Robert_Lennon4
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm a Linguistics Researcher at the [Phonetics Lab](http://wp.lancs.ac.uk/phonetics/) at [Lancaster University](https://www.lancaster.ac.uk/). My research is in sociolinguistics, phonetics and speech perception, and I'm interested in how the social aspects of speech communities affect how speech sounds are produced and perceived.
  
  My expertise is in Scottish English (especially phonetic variation in Glasgow), rhoticity, and cross-dialect perception. I also have some knowledge of perception of speech tempo and phonetic reduction.
  
  I am most skilled in: <mark>Sociolinguistics teaching</mark>, <mark>R</mark>, <mark>Praat</mark> and <mark>Perception experiments</mark>
  
  Click [here](CV/Robert_Lennon_CV.pdf) for my CV.

content:
#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Changing /r/ Accents
#        link: [Project website](http://www.research.lancs.ac.uk/portal/en/upmprojects/changing-r-accents-towards-a-sociophonological-understanding-of-sound-change(c932501b-8414-4b09-85b6-61b890689fe1).html)
#        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
#          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#          #   icon: fab fa-github
#          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#        description: | # this will include new lines to allow paragraphs
#          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: PhD Linguistics
        #caption: 2019
        sub_title: University of Glasgow, 2019
        #quote: >
        #  Supervisors: [Dr Rachel Smith](https://www.gla.ac.uk/schools/critical/staff/rachelsmith/), [Professor Jane Stuart-Smith](https://www.gla.ac.uk/schools/critical/staff/janestuart-smith/)
        description: | # this will include new lines to allow paragraphs   # (http://theses.gla.ac.uk/74370/)
          Thesis: [***Experience and Learning in Cross-dialect perception: Derhoticised /r/ in Glasgow***](papers/LennonPhD2017.pdf)

      - layout: left
        title: MSc Linguistics
        #caption: 2013
        sub_title: University of Glasgow, 2013
        #quote: >
        #  Supervisors: Dr Rachel Smith, Professor Jane Stuart-Smith
        description: | # this will include new lines to allow paragraphs
          Thesis: ***The effect of experience in cross-dialect perception: Parsing /r/ in Glaswegian***

      - layout: left
        title: MA English Language
        #caption: 2012
        sub_title: University of Glasgow, 2012
        #quote: >
        #  Supervisors: Dr Rachel Smith, Professor Jane Stuart-Smith
        description: | # this will include new lines to allow paragraphs
          Dissertation: ***A real-time sociophonetic study of postvocalic /r/ in the speech of schoolchildren in Bearsden***


  - title: Research Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Research Associate
        sub_title: Lancaster University
        caption: 2020 - present
        description: | # this will include new lines to allow paragraphs
            ***Changing /r/ accents? Towards a sociophonological understanding of sound change***
            
            We're using a variety of methods to investigate residual rhoticity in Blackburn, Lancashire (where many speakers still pronounce the /r/ in words like *car* and *third*), examining the mechanisms by which it is changing over time.

      - layout: left
        title: Research Fellow
        sub_title: University of Leeds
        caption: 2017 - 2020
        description: | # this will include new lines to allow paragraphs
            ***Speech tempo perception and missing sounds***
            
            In this project we investigated the link between laboratory measurements of speech tempo and how listeners perceive speaking rate. I designed and ran a suite of speech perception experiments, maintained a large phonetically-aligned corpus, and contributed to analysis, conference presentations and journal submissions.

      - layout: left
        title: Research Assistant
        sub_title: University of Glasgow
        caption: 2012 - 2017
        description: | # this will include new lines to allow paragraphs
            While completing my Phd I worked on multiple funded projects run by researchers from different universities. Tasks included:
            - Statistical analysis, transcription work
            - Writing contributions to research outputs
            - Participant recruitment and recording


  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        description: | # this will include new lines to allow paragraphs
            Plug, L., Lennon, R. & Gold, E. (2021). [Articulation rates' inter-correlations and discriminating powers in an English speech corpus.](https://doi.org/10.1016/j.specom.2021.05.006) *Speech Communication*.

      - layout: left
        description: | # this will include new lines to allow paragraphs  # (http://eprints.whiterose.ac.uk/159167/1/SpeechProsody_4.pdf)
            Plug, L., Smith, R., & Lennon, R. (2020). [Listeners' sensitivity to syllable complexity in speech tempo perception.](papers/PlugLennonSmithSP2020.pdf) *Proceedings of the 10th International Conference on Speech Prosody*. Tokyo: University of Tokyo.

      - layout: left
        description: | # this will include new lines to allow paragraphs  # (https://icphs2019.org/icphs2019-fullpapers/pdf/full-paper_637.pdf)
            Lennon, R., Plug, L. & Gold, E. (2019). [A comparison of multiple speech tempo measures: Inter-correlations and discriminating power.](papers/LennonPlugGoldICPhS2019.pdf) *Proceedings of the 19th ICPhS*. Melbourne: University of Melbourne.

      - layout: left
        description: | # this will include new lines to allow paragraphs  # (https://icphs2019.org/icphs2019-fullpapers/pdf/full-paper_611.pdf)
            Plug, L., Lennon, R. & Smith, R.(2019). [Measured and perceived speech tempo: Canonical vs surface syllable and phone rates.](papers/PlugLennonSmithICPhS2019.pdf) *Proceedings of the 19th ICPhS*. Melbourne: University of Melbourne.

      - layout: left
        description: | # this will include new lines to allow paragraphs  # (https://www.internationalphoneticassociation.org/icphs-proceedings/ICPhS2015/Papers/ICPHS1019.pdf)
            Lennon, R., Smith, R. & Stuart-Smith, J. (2015). [An acoustic investigation of postvocalic /r/ variants in two sociolects of Glaswegian.](papers/LennonSmithStuartSmithICPhS2015.pdf) *Proceedings of the 18th ICPhS*. Glasgow: University of Glasgow.

      - layout: left
        description: | # this will include new lines to allow paragraphs  # (https://www.internationalphoneticassociation.org/icphs-proceedings/ICPhS2015/Papers/ICPHS1028.pdf)
            Stuart-Smith, J., Lennon, R., MacDonald, R., Robertson, D., Soskuthy, M., Jose, B. & Evers, L. (2015). [A dynamic acoustic view of real-time change in word-final liquids in spontaneous Glaswegian.](papers/DynamicLiquidsICPhS2015.pdf) *Proceedings of the 18th ICPhS*. Glasgow: University of Glasgow.


  - title: Selected talks # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        sub_title: Phonetics Lab, Aarhus University
        caption: May 2021
        description: | # this will include new lines to allow paragraphs
            The perception of variable rhoticity in Blackburn, Lancashire: Evidence from an online study. ***(Invited speaker)***

      - layout: left
        sub_title: Phonetics Lab, Lancaster University
        caption: November 2020
        description: | # this will include new lines to allow paragraphs
            Acoustics and perception of Glaswegian /r/. ***(Invited speaker)***

      - layout: left
        sub_title: Speech Prosody 10, University of Tokyo
        caption: May 2020
        description: | # this will include new lines to allow paragraphs
            [Listeners' sensitivity to syllable complexity in speech tempo perception.](http://eprints.whiterose.ac.uk/159167/1/SpeechProsody_4.pdf)    *(Co-author)*

      - layout: left
        sub_title: BAAP, University of York
        caption: April 2020 (postponed)
        description: | # this will include new lines to allow paragraphs
            Quantifying speech tempo: Does the choice of measurement matter?

      - layout: left
        sub_title: Rate and Rhythm in Speech Recognition, Max Planck Institute for Psycholinguistics, Nijmegen
        caption: December 2019
        description: | # this will include new lines to allow paragraphs   #(https://www.mpi.nl/page/r3-poster-program)
            [Speech tempo perception and deletion: Evidence from a listening experiment.](talks/LennonSmithPlugMPI2019.pdf)

      - layout: left
        sub_title: UKLVC 12, Queen Mary University/University College London
        caption: September 2019
        description: | # this will include new lines to allow paragraphs  #(https://uklvc12.qmul.ac.uk/wp-content/uploads/2019/09/TomeLouridoetal_UKLVC12.pdf)
            [The effect of regional variation on speech processing: Evidence from an eye-tracking experiment.](talks/TomeLouridoLennonEvansUKLVC12.pdf) *(Co-author)*

      - layout: left
        sub_title: ICPhS 19, Melbourne
        caption: August 2019
        description: | # this will include new lines to allow paragraphs
            [A comparison of multiple speech tempo measures: Inter-correlations and discriminating power.](https://icphs2019.org/icphs2019-fullpapers/pdf/full-paper_637.pdf)

      - layout: left
        sub_title: ICPhS 19, Melbourne
        caption: August 2019
        description: | # this will include new lines to allow paragraphs
            [Measured and perceived speech tempo: Canonical vs surface syllable and phone rates.](https://icphs2019.org/icphs2019-fullpapers/pdf/full-paper_611.pdf) *(Co-author)*

      - layout: left
        sub_title: IAFPA 28, Istanbul
        caption: July 2019
        description: | # this will include new lines to allow paragraphs
            Comparing alternative speech tempo measures: Inter-correlations and discriminating powers.

#      - layout: left
#        sub_title: Linguistics Colloquium, University of York
#        caption: February 2019
#        description: | # this will include new lines to allow paragraphs
#            [Speech tempo measurement and perception.](https://www.york.ac.uk/language/news/events/talks/colloquia/2019-spring-week7/) (co-presented with Leendert Plug)

      - layout: left
        sub_title: Speech Science Forum seminar, University College London
        caption: October 2018
        description: | # this will include new lines to allow paragraphs
            [Experience and learning in cross-dialect perception: Ambiguous /r/ in Glasgow.](https://www.ucl.ac.uk/pals/sites/pals/files/ssf_rlennon.pdf) ***(Invited speaker)***

      - layout: left
        sub_title: BAAP, University of Kent
        caption: April 2018
        description: | # this will include new lines to allow paragraphs  # (https://blogs.kent.ac.uk/baap/files/2018/03/BAAP-2018_Lennon.pdf)
            [Perception of Glaswegian rhoticity suffers in challenging listening conditions.](talks/LennonBAAP2018.pdf) ***(Invited session chair: Speech Perception)***

#      - layout: left
#        sub_title: Linguistics Research Seminar, University of Glasgow
#        caption: March 2017
#        description: | # this will include new lines to allow paragraphs
#            Fussed, second, thud: Mouse tracking reveals implicit perception of ambiguous /r/ in Glasgow. ***(Invited speaker)***

      - layout: left
        sub_title: Human Language Processing Lab, University of Rochester
        caption: February 2017
        description: | # this will include new lines to allow paragraphs
            Glasgow Smiles Better? Long-term and short-term adaptation to accents. (***Invited speaker***, co-presented with Rachel Smith)

      - layout: left
        sub_title: LabPhon15, Cornell University
        caption: July 2016
        description: | # this will include new lines to allow paragraphs  # (http://intro2psycholing.net/labphon15/long_abstracts/LabPhon15_Revised_abstract_250.pdf)
            [Ambiguous rhoticity in Glasgow: Short term exposure promotes perceptual adaptation for experienced and inexperienced listeners.](talks/LennonLabPhon2016.pdf) *(National Science Foundation travel award, 400USD)*

      - layout: left
        sub_title: R-atics 5, Fryske Akademy, Leeuwarden
        caption: May 2016
        description: | # this will include new lines to allow paragraphs
            Derhoticisation in Glasgow: Do listeners adapt after short term exposure?

#      - layout: left
#        sub_title: BAAP, Lancaster University
#        caption: March 2016
#        description: | # this will include new lines to allow paragraphs
#            [Short term learning of derhoticised /r/ in Glasgow: Adaptation occurs for experienced and inexperienced listeners.](http://wp.lancs.ac.uk/phonetics/files/2015/08/BAAP_abstracts.pdf)

#      - layout: left
#        sub_title: BAAP, Lancaster University
#        caption: March 2016
#        description: | # this will include new lines to allow paragraphs
#            [Is gender a factor in real-time acoustic change in coda liquids in Glasgow?](http://wp.lancs.ac.uk/phonetics/files/2015/08/BAAP_abstracts.pdf) *(Co-author)*

      - layout: left
        sub_title: ICPhS 18, Glasgow
        caption: August 2015
        description: | # this will include new lines to allow paragraphs
            [An acoustic investigation of postvocalic /r/ variants in two sociolects of Glaswegian.](https://www.internationalphoneticassociation.org/icphs-proceedings/ICPhS2015/Papers/ICPHS1019.pdf)

      - layout: left
        sub_title: ICPhS 18, Glasgow
        caption: August 2015
        description: | # this will include new lines to allow paragraphs
            [A dynamic acoustic view of real-time change in word-final liquids in spontaneous Glaswegian.](https://www.internationalphoneticassociation.org/icphs-proceedings/ICPhS2015/Papers/ICPHS1028.pdf) *(Co-author)*

#      - layout: left
#        sub_title: Linguistics Research Seminar, University of Glasgow
#        caption: October 2014
#        description: | # this will include new lines to allow paragraphs
#            The role of experience in accent perception: Parsing /r/ in Glaswegian. ***(Invited speaker)***

      - layout: left
        sub_title: AMLaP 20, University of Edinburgh
        caption: September 2014
        description: | # this will include new lines to allow paragraphs
            The effect of exposure in cross-dialect perception: Hearing ambiguous /r/ variants in Glaswegian.

      - layout: left
        sub_title: BAAP, University of Oxford
        caption: April 2014
        description: | # this will include new lines to allow paragraphs
            Increased exposure can aid perception of ambiguous /r/ variants in Glasgow. ***(Eugenie Henderson prize, Best Oral Presentation)***

      - layout: left
        sub_title: R-atics 4, GIPSA-Lab, Grenoble
        caption: October 2013
        description: | # this will include new lines to allow paragraphs
            The effect of experience in cross-dialect perception: Parsing /r/ in Glaswegian.


































#  - title: Teaching # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: left
#        title: Teaching title 1
#        #sub_title: Lancaster University
#        #caption: 2020 - present
#        description: | # this will include new lines to allow paragraphs
#            ***Teaching*** Text



#![Visitor Count](https://profile-counter.glitch.me/robertlennon50.github.io/count.svg)

#<img src="https://hitcounter.pythonanywhere.com/count/tag.svg" alt="Hits">

#  - title: A Little More About Me
#    layout: text
#    content: | # this will include new lines to allow paragraphs
#      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#      - Rock climbing
#      - Gaming
#      - Knitting
#      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
#      
#      Look at this cool image of Scottish mountains
#      
#      ![Mountains](/images/Isle_of_Skye_Scotland.jpg "Mountains")

# Footer
#footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
